package com.example.urlshortener.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.time.Instant;

/**
 * Persists the mapping between a user-provided long URL and its shortened
 * representation. The primary key {@code id} is auto-generated by JPA
 * (identity/sequence strategy backed by PostgreSQL) and is subsequently
 * Base62-encoded into {@code shortCode}, which is the value exposed to
 * clients as the "key" of the short URL.
 */
@Entity
@Table(name = "url_mapping", uniqueConstraints = {
        @jakarta.persistence.UniqueConstraint(name = "uk_short_code", columnNames = "short_code")
})
public class UrlMapping {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false, updatable = false)
    private Long id;

    @Column(name = "short_code", length = 16)
    private String shortCode;

    @Column(name = "long_url", nullable = false, columnDefinition = "TEXT")
    private String longUrl;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    protected UrlMapping() {
        // JPA no-arg constructor
    }

    public UrlMapping(String longUrl) {
        this.longUrl = longUrl;
        this.createdAt = Instant.now();
    }

    public Long getId() {
        return id;
    }

    public String getShortCode() {
        return shortCode;
    }

    public void setShortCode(String shortCode) {
        this.shortCode = shortCode;
    }

    public String getLongUrl() {
        return longUrl;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }
}
